class Product < ActiveRecord::Base
  attr_accessible :last_updated                              ,
                  :product_id                                ,
                  :name                                      ,
                  :description                               ,
                  :short_description                         ,
                  :image_path                                ,
                  :url                                       ,
                  :intro_apr                                 ,
                  :q_intro_apr                               ,
                  :intro_apr_period                          ,
                  :q_intro_apr_period                        ,
                  :regular_apr                               ,
                  :q_regular_apr                             ,
                  :annual_fee                                ,
                  :q_annual_fee                              ,
                  :credit_needed                             ,
                  :q_credit_needed                           ,
                  :balance_transfers                         ,
                  :q_balance_transfers                       ,
                  :transfer_fee_pin                          ,
                  :q_transfer_fee_pin                        ,
                  :transaction_fee_signature                 ,
                  :q_transaction_fee_signature               ,
                  :load_fee                                  ,
                  :q_load_fee                                ,
                  :atm_fee                                   ,
                  :q_atm_fee                                 ,
                  :activation_fee                            ,
                  :q_activation_fee                          ,
                  :balance_transfer_intro_apr                ,
                  :q_balance_transfer_intro_apr              ,
                  :balance_transfer_intro_apr_period         ,
                  :q_balance_transfer_intro_apr_period       ,
                  :balance_transfer_goto_rate                ,
                  :q_balance_transfer_goto_rate              ,
                  :cash_advance_goto_rate                    ,
                  :q_cash_advance_goto_rate                  ,
                  :penalty_goto_rate                         ,
                  :q_penalty_goto_rate                       ,
                  :late_fee                                  ,
                  :q_late_fee                                ,
                  :cash_advance_fee                          ,
                  :q_cash_advance_fee                        ,
                  :balance_transfer_fee                      ,
                  :q_balance_transfer_fee                    ,
                  :foreign_currency_exchange_fee             ,
                  :q_foreign_currency_exchange_fee           ,
                  :issuer                                    ,
                  :feature_flag                              ,
                  :popular_flag                              ,
                  :low_apr_feature_flag                      ,
                  :rewards_feature_flag                      , 
                  :business_feature_flag                     , 
                  :bad_credit_feature_flag                   , 
                  :student_feature_flag                      
  
  validates :product_id, presence: true, uniqueness: true
  validates(:name, presence: true)
end
